apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: atlas-api-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: atlas-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: atlas-worker-pdb
  namespace: {{ .Values.namespace }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: atlas-worker
