namespace: atlas-platform

image:
  registry: us-central1-docker.pkg.dev/velrite-tf-test/atlas-images
  tag: "06dc1283"
  pullPolicy: IfNotPresent

serviceAccount:
  name: atlas-workload-ksa

redis:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

api:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

scheduler:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

worker:
  replicas: 2
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi
  cpuMillicores: "1000"
  memoryMb: "512"

otel:
  endpoint: "http://otel-collector.otel.svc.cluster.local:4317"
